#
name: Deploys the Sample Hardhat Project creates a new Docker image

on:
  pull_request:
    types:
    - closed
    - labeled
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-hardhat-and-create-new-image:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./hardhat-tutorial

      - name: Compile Hardhat project
        run: npx hardhat compile
        working-directory: ./hardhat-tutorial

      - name: Deploy Smart Contracts
        run: npx hardhat run ignition/modules/Token.js
        working-directory: ./hardhat-tutorial   

      - name: Build and push Docker image          
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:contracts